# Generated by Django 5.2 on 2025-05-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezanimal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaltype',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
    ]
